### ISSUE TITLE
Incorrect link to github 

### ISSUE THREAD

**Issue by bessarabov** [shlomif/perl-Config-IniFiles#4]
In the main POD https://metacpan.org/pod/Config::IniFiles there is a text:

> Please report any bugs or feature requests on the bugtracker website https://github.com/shlomif/Config-IniFiles/issues

But the link is incorrect. It should be `https://github.com/shlomif/perl-Config-IniFiles/issues`

**Comment by shlomif** [comment]
On Thu, 12 Jul 2018 09:04:31 -0700
Ivan Bessarabov <notifications@github.com> wrote:

> In the main POD https://metacpan.org/pod/Config::IniFiles there is a text:
> 
> > Please report any bugs or feature requests on the bugtracker website
> > https://github.com/shlomif/Config-IniFiles/issues  
> 
> But the link is incorrect. It should be
> `https://github.com/shlomif/perl-Config-IniFiles/issues`
> 
> 

thanks! I'll look into it.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
http://www.shlomifish.org/humour/ways_to_do_it.html

I don’t believe in Astrology, because I’m a Taurus, and Tauri never believe in
Astrology.           — Source unknown

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
seems ok now - thanks!
